# -*- coding: utf-8 -*-
"""
================================================================================
Daily Operations - V4.1 Intraday (Hybrid Optimized)
================================================================================
盤中執行腳本 - 專注於 V4.1 策略 (均線特徵增強版) 與 T+20 模型支援

流程:
1. 從 yfinance 下載當日 OHLC 資料 (盤中即時)
2. 成交量使用 CSV 歷史資料的前 5 日平均
3. 使用上述資料訓練 LSTM 模型 (T+20, T+5, T+1)
4. 使用新訓練的 LSTM 進行特徵工程與預測
5. 輸出結果到 intraday_runs_v4/{date}_{time}/
6. 不寫入 twii_data_from_2000_01_01.csv

作者：Phil Liang (Generated by Gemini)
日期：2025-12-13
================================================================================
"""

import os
import sys
import shutil
import pickle
import subprocess
import json
import glob
from datetime import datetime, timedelta

# 設定 UTF-8 輸出
sys.stdout.reconfigure(encoding='utf-8')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
from tensorflow import keras
from keras import layers

# =============================================================================
# 引用主系統
# =============================================================================
import ptrl_hybrid_system as core_system

# =============================================================================
# 設定路徑
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
INTRADAY_RUNS_PATH = os.path.join(PROJECT_PATH, 'intraday_runs_v4')  # V4 專屬資料夾
CSV_FILE = os.path.join(PROJECT_PATH, 'twii_data_from_2000_01_01.csv')

# RL 模型路徑 (僅 V4)
STRATEGY_V4_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v4')

# LSTM 訓練腳本名稱
SCRIPT_5D = "twii_model_registry_5d.py"
SCRIPT_20D = "twii_model_registry_20d.py"
SCRIPT_1D = "twii_model_registry_multivariate.py"

# LSTM 模型預設輸出路徑
DEFAULT_LSTM_5D_DIR = os.path.join(PROJECT_PATH, 'saved_models_5d')
DEFAULT_LSTM_20D_DIR = os.path.join(PROJECT_PATH, 'saved_models_20d')
DEFAULT_LSTM_1D_DIR = os.path.join(PROJECT_PATH, 'saved_models_multivariate')


# =============================================================================
# Step 0: 建立盤中專屬工作區
# =============================================================================
def create_intraday_workspace(date_str: str, time_str: str) -> dict:
    folder_name = f"{date_str}_{time_str}"
    intraday_path = os.path.join(INTRADAY_RUNS_PATH, folder_name)
    paths = {
        'root': intraday_path,
        'lstm_models': os.path.join(intraday_path, 'lstm_models'),
        'lstm_5d': os.path.join(intraday_path, 'lstm_models', 'saved_models_5d'),
        'lstm_20d': os.path.join(intraday_path, 'lstm_models', 'saved_models_20d'),
        'lstm_1d': os.path.join(intraday_path, 'lstm_models', 'saved_models_multivariate'),
        'cache': os.path.join(intraday_path, 'cache'),
        'reports': os.path.join(intraday_path, 'reports'),
    }
    for key, path in paths.items():
        os.makedirs(path, exist_ok=True)
    print(f"[Workspace] 建立盤中工作區: {intraday_path}")
    return paths


# =============================================================================
# 輔助函式: 取得盤中 OHLC
# =============================================================================
def fetch_intraday_ohlc(ticker: str = "^TWII") -> tuple:
    """
    從證交所盤中即時 API 下載當日 OHLC 資料
    """
    import requests
    
    print(f"\n[Download] 正在從證交所盤中 API 下載即時資料...")
    url = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_t00.tw"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Accept': 'application/json',
        'Referer': 'https://mis.twse.com.tw/stock/index.jsp'
    }
    
    try:
        r = requests.get(url, headers=headers, timeout=10)
        r.raise_for_status()
        data = r.json()
        msg_array = data.get('msgArray', [])
        
        if not msg_array:
            print("[Error] 證交所 API 無資料 (可能非交易時段)")
            return None
        
        item = msg_array[0]
        raw_date = item.get('d', '')
        if len(raw_date) == 8:
            date_str = f"{raw_date[:4]}-{raw_date[4:6]}-{raw_date[6:8]}"
        else:
            date_str = datetime.now().strftime('%Y-%m-%d')
        
        o = float(item.get('o', 0))
        h = float(item.get('h', 0))
        l = float(item.get('l', 0))
        z = float(item.get('z', 0))
        time_str = item.get('t', 'N/A')
        
        print(f"  📅 日期: {date_str}")
        print(f"  ⏰ 時間: {time_str}")
        print(f"  📈 Open: {o:.2f}")
        print(f"  📊 High: {h:.2f}")
        print(f"  📉 Low: {l:.2f}")
        print(f"  💰 即時價: {z:.2f}")
        
        return (date_str, o, h, l, z)
        
    except Exception as e:
        print(f"[Error] 取得盤中資料失敗: {e}")
        return None


# =============================================================================
# 輔助函式: 取得前 5 日成交量平均
# =============================================================================
def get_avg_volume_from_csv(n_days: int = 5) -> float:
    print(f"\n[Volume] 從 CSV 計算前 {n_days} 日成交量平均...")
    try:
        df = pd.read_csv(CSV_FILE)
        volumes = df['volume'].tail(n_days)
        avg_vol = volumes.mean()
        print(f"  📈 平均成交量: {avg_vol:.2f} 億元")
        return avg_vol
    except Exception as e:
        print(f"[Error] 讀取 CSV 失敗: {e}")
        return 3000.0


# =============================================================================
# 輔助函式: 建立暫存 CSV
# =============================================================================
def create_temp_csv_with_intraday(intraday_data: tuple, avg_volume: float, workspace: dict) -> str:
    print("\n[TempCSV] 建立暫存訓練資料...")
    df = pd.read_csv(CSV_FILE)
    date_str, o, h, l, c = intraday_data
    dt = datetime.strptime(date_str, '%Y-%m-%d')
    csv_date = f"{dt.year}/{dt.month}/{dt.day}"
    
    last_date = df['date'].iloc[-1]
    last_dt = datetime.strptime(last_date, '%Y/%m/%d')
    
    if last_dt.date() == dt.date():
        print(f"  [Info] 更新 {csv_date} 的資料為盤中數據")
        df.iloc[-1] = [csv_date, o, h, l, c, avg_volume]
    else:
        print(f"  [Info] 加入盤中資料: {csv_date}")
        new_row = pd.DataFrame({
            'date': [csv_date], 'open': [o], 'high': [h], 'low': [l], 'close': [c], 'volume': [avg_volume]
        })
        df = pd.concat([df, new_row], ignore_index=True)
    
    temp_csv_path = os.path.join(workspace['cache'], 'temp_twii_data.csv')
    df.to_csv(temp_csv_path, index=False)
    print(f"  ✅ 暫存 CSV 已建立: {temp_csv_path}")
    return temp_csv_path


# =============================================================================
# Step 1: LSTM 訓練 (包含 T+20, T+5, T+1)
# =============================================================================
def train_lstm_with_intraday(workspace: dict, temp_csv_path: str, end_date: str):
    print("\n" + "=" * 60)
    print("📚 Step 1: LSTM 訓練 (含盤中資料 - V4 Full Suite)")
    print("=" * 60)
    
    end_dt = datetime.strptime(end_date, '%Y-%m-%d')
    start_5d = (end_dt - timedelta(days=2200)).strftime('%Y-%m-%d')
    start_20d = (end_dt - timedelta(days=2400)).strftime('%Y-%m-%d')
    start_1d = (end_dt - timedelta(days=2000)).strftime('%Y-%m-%d')
    split_ratio = "0.99"
    
    backup_csv_path = CSV_FILE + ".bak"
    print(f"\n[Backup] 備份原始 CSV -> {backup_csv_path}")
    shutil.copy2(CSV_FILE, backup_csv_path)
    
    print(f"[Swap] 覆蓋原始 CSV 為盤中資料")
    shutil.copy2(temp_csv_path, CSV_FILE)
    
    training_success = True
    
    try:
        # T+5
        print(f"\n[Training] T+5 Model ({start_5d} ~ {end_date})...")
        cmd_5d = [sys.executable, os.path.join(PROJECT_PATH, SCRIPT_5D), "train", "--start", start_5d, "--end", end_date, "--split_ratio", split_ratio]
        subprocess.run(cmd_5d, check=True, timeout=1200, cwd=PROJECT_PATH)
        
        # T+20
        print(f"\n[Training] T+20 Model ({start_20d} ~ {end_date})...")
        cmd_20d = [sys.executable, os.path.join(PROJECT_PATH, SCRIPT_20D), "train", "--start", start_20d, "--end", end_date, "--split_ratio", split_ratio]
        subprocess.run(cmd_20d, check=True, timeout=1200, cwd=PROJECT_PATH)
        
        # T+1
        print(f"\n[Training] T+1 Model ({start_1d} ~ {end_date})...")
        cmd_1d = [sys.executable, os.path.join(PROJECT_PATH, SCRIPT_1D), "train", "--start", start_1d, "--end", end_date, "--split_ratio", split_ratio]
        subprocess.run(cmd_1d, check=True, timeout=1200, cwd=PROJECT_PATH)
        
        print("\n[Training] ✅ 所有模型訓練完成")
        
    except Exception as e:
        print(f"[Error] 訓練失敗: {e}")
        training_success = False
    finally:
        print(f"\n[Restore] 恢復原始 CSV")
        shutil.copy2(backup_csv_path, CSV_FILE)
        os.remove(backup_csv_path)
    
    if not training_success:
        return False

    print("\n[Archive] 封存模型到盤中工作區...")
    def archive_dir(src_dir, dest_dir):
        if os.path.exists(src_dir):
            if os.path.exists(dest_dir): shutil.rmtree(dest_dir)
            shutil.copytree(src_dir, dest_dir)
            print(f"  ✅ 已封存: {os.path.basename(src_dir)}")
    
    archive_dir(DEFAULT_LSTM_5D_DIR, workspace['lstm_5d'])
    archive_dir(DEFAULT_LSTM_20D_DIR, workspace['lstm_20d'])
    archive_dir(DEFAULT_LSTM_1D_DIR, workspace['lstm_1d'])
    return True


# =============================================================================
# Step 2: 隔離式特徵工程
# =============================================================================
def isolated_feature_engineering_intraday(workspace: dict, intraday_data: tuple, avg_volume: float) -> pd.DataFrame:
    print("\n" + "=" * 60)
    print("🔧 Step 2: 特徵工程 (使用盤中訓練模型)")
    print("=" * 60)
    
    try:
        from twii_model_registry_5d import SelfAttention
    except ImportError:
        print("[Error] 無法引用 twii_model_registry_5d")
        sys.exit(1)

    def load_model_components(model_dir):
        keras_files = glob.glob(os.path.join(model_dir, "*.keras"))
        if not keras_files: return None, None, None, None
        latest_keras = sorted(keras_files)[-1]
        model = keras.models.load_model(latest_keras, custom_objects={'SelfAttention': SelfAttention})
        
        meta_file = latest_keras.replace('model_', 'meta_').replace('.keras', '.json')
        meta = {}
        if os.path.exists(meta_file):
            with open(meta_file, 'r', encoding='utf-8') as f: meta = json.load(f)

        scaler_feat_file = latest_keras.replace('model_', 'feature_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_feat_file): scaler_feat_file = latest_keras.replace('model_', 'scaler_').replace('.keras', '.pkl')
        with open(scaler_feat_file, 'rb') as f: scaler_feat = pickle.load(f)

        scaler_tgt_file = latest_keras.replace('model_', 'target_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_tgt_file): scaler_tgt = scaler_feat
        else:
            with open(scaler_tgt_file, 'rb') as f: scaler_tgt = pickle.load(f)
            
        return model, scaler_feat, scaler_tgt, meta

    print("[Model Injection] 載入盤中訓練的 LSTM 模型...")
    m5d, sf5d, st5d, meta5d = load_model_components(workspace['lstm_5d'])
    m20d, sf20d, st20d, meta20d = load_model_components(workspace['lstm_20d'])
    m1d, sf1d, st1d, meta1d = load_model_components(workspace['lstm_1d'])
    
    if m5d is None or m20d is None or m1d is None:
        print("[Error] 模型載入失敗")
        sys.exit(1)

    if not hasattr(core_system, '_LSTM_MODELS'): core_system._LSTM_MODELS = {}
    core_system._LSTM_MODELS.update({
        'model_5d': m5d, 'scaler_feat_5d': sf5d, 'scaler_tgt_5d': st5d, 'meta_5d': meta5d,
        'model_20d': m20d, 'scaler_feat_20d': sf20d, 'scaler_tgt_20d': st20d, 'meta_20d': meta20d,
        'model_1d': m1d, 'scaler_feat_1d': sf1d, 'scaler_tgt_1d': st1d, 'meta_1d': meta1d,
        'loaded': True
    })
    print("  ✅ 注入完成 (T+1, T+5, T+20)")

    # 合併資料
    print("\n[Merge] 合併歷史資料與盤中資料...")
    df = pd.read_csv(CSV_FILE)
    df['date'] = pd.to_datetime(df['date'], format='%Y/%m/%d')
    df = df.set_index('date')
    df = df.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'volume': 'Volume'})
    
    date_str, o, h, l, c = intraday_data
    intraday_dt = pd.Timestamp(date_str)
    
    if intraday_dt in df.index:
        df.loc[intraday_dt] = [o, h, l, c, avg_volume]
    else:
        new_row = pd.DataFrame({'Open': [o], 'High': [h], 'Low': [l], 'Close': [c], 'Volume': [avg_volume]}, index=[intraday_dt])
        df = pd.concat([df, new_row])
    
    df = df.sort_index()
    return core_system.calculate_features(df, df, ticker="^TWII", use_cache=False)


# =============================================================================
# Step 3: V4 策略推論
# =============================================================================
def v4_inference(workspace: dict, df: pd.DataFrame) -> dict:
    print("\n" + "=" * 60)
    print("🎯 Step 3: V4 策略推論 (盤中預測)")
    print("=" * 60)
    
    from stable_baselines3 import PPO
    latest = df.iloc[-1]
    signal_buy_filter = bool(latest.get('Signal_Buy_Filter', False))
    print(f"  [濾網] Signal_Buy_Filter = {signal_buy_filter}")
    
    features = np.array([latest.get(col, 0.0) for col in core_system.FEATURE_COLS], dtype=np.float32).reshape(1, -1)
    features = np.nan_to_num(features, nan=0.0, posinf=1.0, neginf=-1.0)
    
    # 載入 V4 模型
    buy_path = os.path.join(STRATEGY_V4_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(STRATEGY_V4_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        return {'error': 'V4 Model not found', 'filter_status': signal_buy_filter}

    try:
        buy_agent = PPO.load(buy_path)
        sell_agent = PPO.load(sell_path)
        
        b_act, _ = buy_agent.predict(features, deterministic=True)
        b_obs = buy_agent.policy.obs_to_tensor(features)[0]
        b_prob = buy_agent.policy.get_distribution(b_obs).distribution.probs.detach().cpu().numpy()[0]
        
        ai_action = 'BUY' if b_act[0] == 1 else 'WAIT'
        buy_prob = float(b_prob[1]) if b_act[0] == 1 else float(b_prob[0])
        
        buy_signal = ai_action if signal_buy_filter else f"FILTERED (AI: {ai_action})"
        print(f"  [V4] Buy: {buy_signal} ({buy_prob:.1%})")
        
        sell_scenarios = {}
        for scenario_name, return_value in {'cost': 1.00, 'profit': 1.10, 'loss': 0.95}.items():
            s_feat = np.concatenate([features[0], [return_value]]).reshape(1, -1)
            s_act, _ = sell_agent.predict(s_feat, deterministic=True)
            sell_scenarios[scenario_name] = 'SELL' if s_act[0] == 1 else 'HOLD'
        
        return {
            'filter_status': signal_buy_filter,
            'buy_signal': buy_signal,
            'buy_prob': buy_prob,
            'ai_action': ai_action,
            'sell_scenarios': sell_scenarios
        }
    except Exception as e:
        print(f"  [Error] V4 Inference: {e}")
        return {'error': str(e), 'filter_status': signal_buy_filter}


# =============================================================================
# Step 4: 輸出盤中報告
# =============================================================================
def generate_intraday_report(workspace: dict, df: pd.DataFrame, res: dict, date_str: str, intraday_data: tuple, avg_volume: float):
    print("\n" + "=" * 60)
    print("📊 Step 4: 盤中戰情儀表板 (V4)")
    print("=" * 60)
    
    last = df.iloc[-1]
    filter_status = res.get('filter_status', False)
    _, o, h, l, c = intraday_data
    
    lines = []
    lines.append("=" * 50)
    lines.append(f"📅 盤中即時分析 - {date_str}")
    lines.append(f"⏰ 更新時間: {datetime.now().strftime('%H:%M:%S')}")
    lines.append("=" * 50)
    lines.append(f"📊 Open:  {o:,.2f}")
    lines.append(f"📈 High:  {h:,.2f}")
    lines.append(f"📉 Low:   {l:,.2f}")
    lines.append(f"💰 Close: {c:,.2f} (即時)")
    lines.append(f"📦 Volume: {avg_volume:.2f} 億元 (前5日平均估計)")
    lines.append("-" * 50)
    
    filter_icon = "✅" if filter_status else "🚫"
    lines.append(f"🎯 [濾網狀態] {filter_icon} {'通過' if filter_status else '未通過 (非突破日)'}")
    lines.append("-" * 50)
    
    # LSTM
    lines.append("🔮 [分析師 LSTM] (盤中訓練)")
    current_close = float(c)
    pred_1d_pct = last.get('LSTM_Pred_1d', 0)
    price_1d = current_close * (1 + pred_1d_pct)
    
    pred_5d_pct = last.get('LSTM_Pred_5d', 0)
    price_5d = current_close * (1 + pred_5d_pct)
    
    pred_20d_pct = last.get('LSTM_Pred_20d', 0)
    price_20d = current_close * (1 + pred_20d_pct)

    lines.append(f"   T+1 預測: {pred_1d_pct*100:+.2f}% (目標價: {price_1d:,.2f}) | 信心度: {last.get('LSTM_Conf_1d', 0)*100:.1f}%")
    lines.append(f"   T+5 預測: {pred_5d_pct*100:+.2f}% (目標價: {price_5d:,.2f}) | 信心度: {last.get('LSTM_Conf_5d', 0)*100:.1f}%")
    lines.append(f"   T+20 預測: {pred_20d_pct*100:+.2f}% (目標價: {price_20d:,.2f}) | 信心度: {last.get('LSTM_Conf_20d', 0)*100:.1f}%")
    lines.append("-" * 50)

    # [New] V4 顯性特徵列表
    lines.append("📐 [關鍵特徵 V4]")
    lines.append(f"   MA20 動能: {last.get('Feat_MA20_Slope', 0)*100:+.2f}%  (>0 轉強)")
    lines.append(f"   市場體制: {last.get('Feat_Trend_Gap', 0)*100:+.2f}%  (>0 多頭結構)")
    lines.append(f"   短線乖離: {last.get('Feat_Bias_MA20', 0)*100:+.2f}%")
    lines.append(f"   季線距離: {last.get('Feat_Dist_MA60', 0)*100:+.2f}%")
    lines.append(f"   年線位置: {last.get('Feat_Dist_MA240', 0)*100:+.2f}%  (>0 長多)")
    lines.append(f"   相對量能: {last.get('Feat_Vol_Ratio', 0):.2f}x   (>1.0 放量)")
    lines.append("-" * 50)
    
    # V4 RL
    lines.append("🤖 [操盤手 V4]")
    if 'error' in res:
        lines.append(f"   ❌ 錯誤: {res['error']}")
    else:
        buy_signal = res['buy_signal']
        buy_prob = res['buy_prob']
        buy_icon = "🚀" if buy_signal == 'BUY' else "💤" if buy_signal == 'WAIT' else "🚫"
        
        lines.append(f"   🛒 買入訊號: {buy_icon} {buy_signal} ({buy_prob:.1%})")
        ss = res.get('sell_scenarios', {})
        lines.append(f"   📦 賣出建議:")
        lines.append(f"      ├─ 成本區 (0%):  {ss.get('cost', 'N/A')}")
        lines.append(f"      ├─ 獲利中 (+10%): {ss.get('profit', 'N/A')}")
        lines.append(f"      └─ 虧損中 (-5%):  {ss.get('loss', 'N/A')}")

    lines.append("-" * 50)
    
    # Advice
    ai_action = res.get('ai_action', 'N/A')
    if not filter_status:
        advice = f"🚫 濾網攔截 (AI: {ai_action})"
    elif ai_action == 'BUY':
        advice = "⭐⭐ V4 強力買進 (Strong Buy) ⭐⭐"
    elif ai_action == 'WAIT':
        advice = "💤 空手觀望 (Wait)"
    else:
        advice = "❓ 訊號不明"
        
    lines.append(f"💡 盤中建議: {advice}")
    lines.append("=" * 50)
    
    report = "\n".join(lines)
    print(report)
    
    # Save
    with open(os.path.join(workspace['reports'], 'intraday_summary.txt'), 'w', encoding='utf-8') as f:
        f.write(report)
    
    json_data = {
        'date': date_str,
        'filter_status': filter_status,
        'market': {'close': c, 'volume_est': avg_volume},
        'lstm': {
            'pred_1d': float(pred_1d_pct), 'price_1d': float(price_1d),
            'pred_5d': float(pred_5d_pct), 'price_5d': float(price_5d),
            'pred_20d': float(pred_20d_pct), 'price_20d': float(price_20d),
        },
        'v4': res,
        'advice': advice
    }
    with open(os.path.join(workspace['reports'], 'intraday_summary.json'), 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[Report] 已儲存至: {workspace['reports']}")


# =============================================================================
# Main
# =============================================================================
def main():
    now = datetime.now()
    date_str = now.strftime('%Y-%m-%d')
    time_str = now.strftime('%H%M%S')
    
    print(f"🚀 V4 盤中分析系統 - {date_str} {time_str}")
    
    # Step 0
    ws = create_intraday_workspace(date_str, time_str)
    
    # Step 0.5
    intraday_data = fetch_intraday_ohlc("^TWII")
    if not intraday_data: sys.exit(1)
    
    # Step 0.6
    avg_volume = get_avg_volume_from_csv(5)
    
    # Step 0.7
    temp_csv = create_temp_csv_with_intraday(intraday_data, avg_volume, ws)
    
    # Step 1
    if not train_lstm_with_intraday(ws, temp_csv, intraday_data[0]): sys.exit(1)
    
    # Step 2
    df = isolated_feature_engineering_intraday(ws, intraday_data, avg_volume)
    
    # Step 3
    res = v4_inference(ws, df)
    
    # Step 4
    generate_intraday_report(ws, df, res, intraday_data[0], intraday_data, avg_volume)
    print("Done.")

if __name__ == "__main__":
    main()
